"use client";
import { useEffect, useRef, useState } from 'react';

// Wraps an imported SVG React component (via ?component) and toggles the 'active' class
// to trigger CSS-based transition animations generated by tools like SVG Artista.
// Props:
// - Icon: React component for the SVG (import Icon from '...svg?component')
// - title: accessible title
// - auto: boolean, auto-trigger animation on mount (default true)
// - hover: boolean, also trigger on hover (default true)
// - className: applied to container
// - size: number or string for width/height
export default function AnimatedSvgIcon({ Icon, title = 'icon', auto = true, hover = true, className = '', size = 200 }) {
  const [active, setActive] = useState(false);
  const ref = useRef(null);

  useEffect(() => {
    if (auto && typeof window !== 'undefined') {
      const mediaQuery = window.matchMedia('(prefers-reduced-motion: reduce)');
      if (!mediaQuery.matches) {
        // Minimal delay to ensure CSS selectors apply after mount
        const t = setTimeout(() => setActive(true), 50);
        return () => clearTimeout(t);
      }
    }
  }, [auto]);

  return (
    <div
      ref={ref}
      className={className}
      onMouseEnter={() => hover && setActive(true)}
      onMouseLeave={() => hover && setActive(false)}
    >
      {Icon ? (
        <Icon
          width={size}
          height={size}
          role="img"
          aria-label={title}
          className={active ? 'active' : ''}
        />
      ) : null}
    </div>
  );
}
